# This workflow will upload the codenav package using Twine (after manually triggering it)
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Publish PYPI Packages

on:
  workflow_dispatch:

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools twine
      - name: Build and publish
        env:
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python scripts/release.py
          twine upload -u __token__ dist/*